# Generated by Django 3.2.17 on 2023-02-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='سعر الكشف: '),
        ),
    ]
