# Generated by Django 3.2.17 on 2023-02-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='الهاتف: '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='waiting_time',
            field=models.IntegerField(max_length=2, verbose_name='مدة الأنتظار بالدقيقة'),
        ),
    ]
