# Generated by Django 3.2.17 on 2023-02-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20230209_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_us',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='وقت الإنضمام: '),
            preserve_default=False,
        ),
    ]
