# Generated by Django 3.2.17 on 2023-02-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_join_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='join_us',
            new_name='join_new',
        ),
    ]
