# Generated by Django 3.2.17 on 2023-02-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_waiting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='join_new',
        ),
        migrations.AlterField(
            model_name='profile',
            name='waiting_time',
            field=models.IntegerField(max_length=2, verbose_name='مدة الأنتظار بالدقيقة'),
        ),
    ]
