# Generated by Django 3.2.17 on 2023-02-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_join_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='سعر الكشف: '),
            preserve_default=False,
        ),
    ]
