# Generated by Django 3.2.17 on 2023-02-10 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_profile_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='join_us',
        ),
    ]
