# Generated by Django 3.2.17 on 2023-02-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_profile_join_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_us',
            field=models.CharField(default='', max_length=20),
        ),
    ]
