# Generated by Django 3.2.17 on 2023-02-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_profile_join_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=5, null=True, verbose_name='الجنس: '),
        ),
    ]
