# Generated by Django 3.2.17 on 2023-02-10 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
