# Generated by Django 3.2.17 on 2023-02-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_profile_join_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(choices=[('أنف وأذن  وحنجرة', 'أنف وأذن  وحنجرة'), ('أمراض دم', 'أمراض دم'), ('نفسي', 'نفسي'), ('جلدية', 'جلدية'), ('اطفال حديثي الولادة', 'اطفال حديثي الولادة'), ('قلب و اوعيه دموية', 'قلب و اوعيه دموية'), ('أسنان', 'أسنان'), ('أورام', 'أورام'), ('نساء وتوليد', 'نساء وتوليد'), ('عظام', 'عظام'), ('مخ وأعصاب', 'مخ وأعصاب')], max_length=50, verbose_name='دكتور؟'),
        ),
    ]
